services:
  admin-2-vite:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    pull_policy: always
    restart: always
    network_mode: host
    environment:
      SHM_HOST: http://127.0.0.1:8080
      VITE_SHOW_SWAGGER: "true"
      VITE_BASE_PATH: /
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  admin-2-nginx:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
      target: admin-2-nginx
    restart: always
    network_mode: host
    environment:
      - VITE_HOST=127.0.0.1
      - VITE_SHOW_SWAGGER=true
      - SHM_HOST=http://127.0.0.1:8080
      - SHM_BASE_PATH=/
